"""Константы проекта."""

MIN_SEATS = 1
INVALID_SEATS_MESSAGE = f'Количество мест должно быть не меньше {MIN_SEATS}'
RESERVATION_CUSTOMER_NAME_MAX_LENGTH = 50
SECONDS_IN_MINUTE = 60
TABLE_LOCATION_MAX_LENGTH = 50
TABLE_NAME_MAX_LENGTH = 50
