# Generated by Django 3.2.16 on 2025-04-14 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество мест должно быть не меньше 1')], verbose_name='Количество мест')),
                ('location', models.CharField(max_length=50, verbose_name='Местоположение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('reservation_time', models.DateTimeField(unique=True, validators=[utils.functions.validate_date], verbose_name='Время бронирования')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='Длительность брони в минутах')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.table', verbose_name='Столик')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'Брони',
                'default_related_name': 'reservations',
            },
        ),
    ]
